whyrusleeping/gx

- main.go
In general it looks like the help writing style needs to be standardized. When are we using capitalization? When are we using complete sentences? Should there always be an EXAMPLES section?
> Correct spelling and punctuation in version help

- gxutil/publish.go
Not sure if this is the best approach to cross platform compatibility in Go, but this patch fixes my issue with `gx publish` under windows.
Fixes https://github.com/whyrusleeping/gx/issues/39
> Fix windows path slash bug

- main.go
In https://github.com/ipfs/go-ipfs/pull/2545 @whyrusleeping wrote "i think the best way to do that right now is to do something like gx deps | grep iptb | awk '{ print $2 }'. I need to add something to gx deps to make that query easier"
This PR add the `find` subcommand to `gx deps` so that one can do `gx deps find iptb` instead of the above command.
> main: add `gx deps find <dep>`

- tests/t0030-import.sh
This should fix the expected output from `gx deps --tree` in t0030.
> t0030: fix deps tree expected output

- .travis.yml
- gxutil/pkgfile.go
- tests/t0010-init.sh
The Go JSON encoder escapes characters such as < and > in its output by default, resulting in "author" strings like `foo <foo@bar.io>` being read from package.json correctly, but on any writes gx does to the file it is written as `foo \u003cfoo@bar.io\u003e`. `jq` seems to unescape these when reading, which kept the issue from surfacing in sharness tests.
This was done as a safety precaution to keep HTML from being embedded in JSON payloads, but this does not seem to apply in the case of a package.json file.
This patch modifies the package.json writing logic to not escape HTML.
> Do not escape HTML in package.json output.

- gxutil/pm.go
- package.json
- tests/t0010-init.sh
This is to include https://github.com/whyrusleeping/gx/pull/94 as a patch-level (bugfix) version bump. I don't think I can push a tag in a PR, so that will have to be done on your end.
> Bump version to 0.9.1.

- Makefile
- bin/check_go_version
- bin/check_version
As gx now only works with go 1.7 or higher, let's check that
before building.
To perform this check, this adds the following shell scripts:
- bin/check_go_version
- bin/check_version
These scripts are copied from go-ipfs.
> Makefile: add check for go version

- tests/.gitignore
When running tests like `./t0010-init.sh -v -i` in tests/, trash directories are left on purpose to make it easy to debug a failing test. Let's ignore these directories.
> tests: ignore 'trash directory.*.sh/'

- main.go
The first time I used import I had to lookup the gx readme to
figure out how to actully use it. It was not clear if it expects:
* mHash
* mHash/pkgname
* ipfs/mHash
* fs:/ipfs/mHash
* etc.
> gx import: add example to CLI help.

- README.md
It is not obvious that package.json can be used by many
different packaging systems, this is now stated
> Update README on package.json

- .gitignore
https://github.com/whyrusleeping/gx/pull/155#commitcomment-26911530
Windows file extensions were not ignored and I accidentally committed a build of gx, this amends that.
> Removes and prevents accidental binaries

- gxutil/get.go
`go-os-rename` is now redundant, the Go standard Rename() uses the same method now and is standard across platforms.
In addition, it never worked to replace directories, only files. If one exists already it will cause an "Access is denied" error on Windows.
> Fix existing package directory

- check.go
- main.go
Checks for:
* Duplicate imports. Unlike `gx deps dupes`, the user won't need to follow up
with a call to `gx deps --tree --highlight=...`.
* Package version mismatch (version in dep list doesn't match version in
package).
* Package name mismatch (name in dep list doesn't match name in package).
It also exits with an exit status of 1 if something needs to be fixed so we can
run it from CI.
names listed under the duplicate import warnings are the *parents* that import
that package. I could append "imported by" to the "$version $hash" line but
that looks a bit funny...
Running this on go-ipfs right now prints out:
```
package protobuf imported as:
- 0.0.0 QmT6n4mspWYEya864BhCUJEgyxiRfmiSY9ruQwTUNpRKaM
- client_golang
- client_model
- common
- golang_protobuf_extensions
- go-ipfs
- 0.0.0 …
```
> add a deps check command

- check.go
* Sort the output of deps check (easier to read at a glance):
* Sort duplicate dependencies by ascending version.
* Sort packages by name.
Also, warn if a version number doesn't parse with semver.
> sort the output of check (and check that versions parse)

- README.md
It looks like a number of gx related tools are not referenced in the README. Let's reference them, as it can help people who are interested in using gx with another language/environment if they can easily find them.
> README: add info about other gx related tools

- gxutil/pm.go
```
gxutil: unify dependency fetching in `InstallDeps`
The previous implementation spawned multiple goroutines to fetch packages but
for the dependencies of one package at a time. This meant that the last
goroutine that took longer to finish (probably because it was fetching the
biggest dependency) held the start of more goroutines to fetch the dependencies
of the packages already fetched.
Unify all the dependencies in a single queue (abstracted in the new
`DependencyQueue` structure) so as soon as new dependencies of a fetched package
are available new goroutines can be spawned to fetch them.
Raise the number of parallel goroutines fetching packages (now `maxGoroutines`)
from 2 to 20 now that this bigger number can be leveraged from this unification.
Remove the retry logic around …
```
> Unify dependency fetching

- gxutil/get.go
- gxutil/lckfile.go
- gxutil/pm.go
- main.go
This is basic support for a lock-file concept discussed between @Stebalien and @whyrusleeping this week.
See also: https://github.com/whyrusleeping/gx-go/pull/49
> Basic lockfile support

- .gx/lastpubver
- gxutil/publish.go
- package.json
This gxs Gx. This is branched off from the 0.13.0 tag.
Note that GxVersion string is set to 0.12.1 even though 0.13.0 is tagged, thus
package.json gx version appears as 0.12.1, but it's 0.13.0 in reality.
Fixes #212
> Feat: gxs gx

- gxutil/get.go
Intended to close https://github.com/whyrusleeping/gx/issues/209. Successfully tested on `go-ipfs` repo.
cc @Stebalien
> Use relative paths for gx lock symlinks

- contrib/README.md
- contrib/gx-changelog.sh
Loosely based on the one in go-ipfs but substantially improved. This script:
1. Is recursive.
2. Is less likely to produce garbage changelog entries
3. Can filter out noisy PRs (e.g., gx updates).
> contrib: add a recursive changelog generation script

- main.go
We can assume a unix-like shell and it:
1. Simplifies this code and removes weird corner cases where gx deviates from bash.
2. Makes it easy to run multiple commands.
> hooks: use sh

- main.go
This patch sets the following environment variables when running the release command:
* `$GX_VERSION` (replaces `$VERSION`)
* `$GX_NAME`
* `$GX_AUTHOR`
* `$GX_LICENSE`
* `$GX_LANGUAGE`
* `$GX_HASH`
This makes it possible to include things like the hash in the release commit message/tag.
> releaseCmd: define additional variables

- gxutil/pm.go
Bump GxVersion to 0.14.2
to avoid a 0.14.1 version claiming to be 0.14.0
in output of `gx -v`
> Bump GxVersion to 0.14.2
