whyrusleeping/gx

Makefile

I wonder if this is a general solution. It didn't work until I group them in 1 line.

Make GOPATH work

---

main.go

Fix gx install bug where language hardcoded to go

---

Makefile
appveyor.yml
gxutil/config.go
gxutil/publish.go
gxutil/repo.go
gxutil/shell.go
main.go
repo.go
tests/Makefile

Try to fix basic usage on windows

Windows fixes

---

README.md

rouh! ping @whyrusleeping for tweaks/additions

readme background

---

.travis.yml
gxutil/publish.go
tests/Makefile
tests/scripts/install-jq.sh
tests/t0010-init.sh
tests/t0030-import.sh
tests/t0040-update.sh

things arent quite working in CI. i'm trying to get them up to par

trying to debug CI

---

gxutil/config.go
gxutil/pkgfile.go
main.go
package.json
tests/t0015-config.sh

This should allow extra fields to live in the package.json file without being clobbered, needs tests

work on making package.json happier living alongside other fields

---

gxutil/pm.go

If you publish your package, add `.gx/lastpubver` to git, and push it to github, you will be able to do `gx import github.com/you/yourpackage`.

basic support for importing gx packages from github

---

main.go

Requires https://github.com/whyrusleeping/json-filter/pull/1

Add set command

---

gxutil/pm.go
main.go
tests/Makefile
tests/lib/test-lib.sh
tests/t0010-init.sh
tests/t0060-publish.sh

Also two little test-lib fixes.

publish: check API is online, clarifies failure UX

---

README.md

_verb (used without object), believed, believing._
1. to have confidence in the truth, the existence, or the reliability of something, although without absolute proof that one is right in doing so: Only if one believes in something can one act purposefully.
_verb (used with object), believed, believing._
2. to have confidence or faith in the truth of (a positive assertion, story, etc.); give credence to.
3. to have confidence in the assertions of (a person).

http://www.dictionary.com/browse/believe

---

gxutil/pm.go
main.go
tests/t0030-import.sh

I would love it if anyone would try this out and provide feedback

improve install UI a bit

---

diff.go
gxutil/get.go
main.go
repo.go
ui.go

I experienced a panic crash running `gx deps find` and noticed that the fix and other useful cleanups were in [this older PR](https://github.com/whyrusleeping/gx/pull/87). Rebased the`feat/cleanup` branch onto master so it can be merged.

Rebased cleanup

---

diff.go
gxutil/get.go
gxutil/pm.go
gxutil/publish.go
gxutil/shell.go
main.go
update.go

I ran `gometalinter` while making some changes, it caught several actual issues related to Errorf calls, and made some simplification suggestions, there is also a single change to conform to error conventions (don't end in a period).
I committed the suggested changes excluding: warnings about shadowing vars, documentation, and permission/security settings. I don't plan on addressing those.

Low hanging lint changes

---

gxutil/pm.go

Further cleanup path detection

---

tests/t0030-import.sh

Fixes test bug introduced in non-PR commit.

test: fix: "install output looks good", added hash

---

main.go

Do not add dependencies to package file twice.

---

main.go

This makes `gx deps dupes` point at which packages are responsible for duplicate imports. For example this is output with broken go-resueport in go-ipfs:
```
package go-log imported with multiple hashes (mostly as QmcuXC5cxs79ro2cUuHs4HQ2bkDLJUYokwL8aivcX6HW3C):
as QmcVVHfdyv15GVPk7NrxdWjh2hLVccXnoD8j2tyQShiXJb by go-reuseport
package gogo-protobuf imported with multiple hashes (mostly as QmdxUuburamoF6zF9qjeQC4WYcWGbWuRmdLacMEsW8ioD8):
as QmZ4Qi3GaRbjcx28Sme5eMH7RQjGkt8wHxt2a65oLaeFEV by go-log
package go-logging imported with multiple hashes (mostly as QmQvJiADDe7JR4m968MwXobTCCzUqQkP87aRHe29MEBGHV):
as QmcaSwFc5RBg8yCq54QURwEU4nwjfCpjbpmaAm4VbdGLKv by go-log
```

Improve gx deps dupes

---

README.md

Mention IPFS_PATH

---

README.md

Fixed small grammatical errors and changed some sentences to be more concise

Fixed minor errors in README.md

---

README.md
go.mod
go.sum
main.go
repo.go

urfave/cli v2 has an incompatible change, for details see https://github.com/urfave/cli/issues/459

Use pointers for CLI flags
